const products = [
  {
    id: 1,
    title: 'Hawaiana',
    description: 'This is pizza 1',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    sizesPrices: [
      { price: 7900, size: 'Mini' },
      { price: 27900, size: 'Mediana' },
      { price: 37900, size: 'Grande' },
    ],
    drinks: [{ name: 'Gaseosa Pepsi' }, { name: 'Gaseosa Manzana' }],
    minPrice: 7900,
    maxPrice: 37900,
    badge: 1,
    coverImage: './images-products/pizza1.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 2,
    title: 'Carnes',
    description: 'This is pizza 2',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    sizesPrices: [
      { price: 7900, size: 'Mini' },
      { price: 27900, size: 'Mediana' },
      { price: 37900, size: 'Grande' },
    ],
    drinks: [{ name: 'Gaseosa Pepsi' }, { name: 'Gaseosa Manzana' }],
    minPrice: 7900,
    maxPrice: 37900,
    badge: 1,
    coverImage: './images-products/pizza2.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 3,
    title: 'Pollo y Champiñones',
    description: 'This is pizza 3',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    sizesPrices: [
      { price: 7900, size: 'Mini' },
      { price: 27900, size: 'Mediana' },
      { price: 37900, size: 'Grande' },
    ],
    drinks: [{ name: 'Gaseosa Pepsi' }, { name: 'Gaseosa Manzana' }],
    minPrice: 7900,
    maxPrice: 37900,
    badge: 1,
    coverImage: './images-products/pizza3.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 4,
    title: 'Pepperoni',
    description: 'This is pizza 4',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    sizesPrices: [
      { price: 8900, size: 'Mini' },
      { price: 29900, size: 'Mediana' },
      { price: 41900, size: 'Grande' },
    ],
    drinks: [{ name: 'Gaseosa Pepsi' }, { name: 'Gaseosa Manzana' }],
    minPrice: 8900,
    maxPrice: 41900,
    badge: 1,
    coverImage: './images-products/pizza4.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
]

export default products
