const cards = [
  {
    id: 1,
    title: 'Pizza 1',
    description: 'This is pizza 1',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza1.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 2,
    title: 'Pizza 2',
    description: 'This is pizza 2',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza2.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 3,
    title: 'Pizza 3',
    description: 'This is pizza 3',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza3.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 4,
    title: 'Pizza 4',
    description: 'This is pizza 4',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza4.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 5,
    title: 'Pizza 5',
    description: 'This is pizza 5',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza5.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 6,
    title: 'Pizza 6',
    description: 'This is pizza 6',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza6.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 7,
    title: 'Pizza 7',
    description: 'This is pizza 7',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza7.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 8,
    title: 'Pizza 8',
    description: 'This is pizza 8',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza8.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
  {
    id: 9,
    title: 'Pizza 9',
    description: 'This is pizza 9',
    ingredients: ['Salsa', 'Mozzarella', 'Piña'],
    price: 34000,
    badge: 1,
    coverImage: './images-products/pizza9.jpg',
    images: [
      './images-products/pizza1.jpg',
      './images-products/pizza2.jpg',
      './images-products/pizza3.jpg',
    ],
  },
]

export default cards
